name: 'Scan Security'
description: 'Security Scan with Microsoft Security Devops'

on:
  workflow_dispatch:
    inputs:
      project-directory:
        description: 'The directory containing the project to scan'
        required: true
        type: string
        default: './'
        
  workflow_call:
    inputs:
      project-directory:
        description: 'The directory containing the project to scan'
        required: true
        type: string
        default: './'

jobs:
  scan:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            5.0.x
            6.0.x
      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@preview
        id: msdo
      # TODO(AS): Getting unrecognized named-value on the env var
      # - name: Upload results to Security tab
      #  uses: github/codeql-action/upload-sarif@v2
      #  with:
      #    sarif_file: ${{ steps.msdo.outputs.sarifFile }}
