# lint-rust.yml
name: 'Lint Rust'
description: 'Lints a Rust project using cargo fmt and cargo clippy'

on:
  workflow_dispatch:
    inputs:
    project-directory:
      description: 'The directory containing the Rust project to lint'
      required: true
      type: string
  workflow_call:
    inputs:
      project-directory:
        description: 'The directory containing the Rust project to lint'
        required: true
        type: string
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.event.inputs.project-directory }}
    steps:
      - name: Lint with cargo fmt
        run: cargo fmt -- --check
      - name: Lint with cargo clippy
        run: cargo clippy -- -D warnings
