# scan-secrets.yml
# https://github.com/marketplace/actions/trufflehog-oss
# - name: TruffleHog OSS
#  uses: trufflesecurity/trufflehog@main
  # with:
    # Repository path
    # path:
    # Start scanning from here (usually main branch).
    # base:
    # Scan commits until here (usually dev branch).
    # head: # optional
    # Extra args to be passed to the trufflehog cli.
    # extra_args: --debug --only-verified
name: 'TruffleHog Secrets Scan'
description: 'Scan for secrets and credentials in a repo'

on:
  workflow_dispatch:
    inputs:
      project-directory:
        description: 'The directory containing the project to scan'
        required: true
        type: string
        default: './'
        
  workflow_call:
    inputs:
      project-directory:
        description: 'The directory containing the project to scan'
        required: true
        type: string
        default: './'

on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: {{ github.event.inputs.project-directory }}
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
